export const SITE = {
  name: "Gonzalo Gimenez",
  firstName: "Gonzalo",
  lastName: "Gimenez",
  role: "Data & AI Engineer",
  roles: "AI Engineer · Data Analyst · Data Engineer",
  location: "Buenos Aires, Argentina",
  coverLabel: "Portfolio personal",
  subtitle:
    "AI Engineer, Data Analyst y Data Engineer. IA que responde con datos verificados.",
  github: "https://github.com/Gonzalo-Gimenez",
  linkedin: "https://www.linkedin.com/in/gonzalo-gimenez-/",
  email: "gonzalodangimenez@gmail.com",
  phone: "+54 11 3430-7458",
  phoneHref: "tel:+541134307458",
  cvPath: "/cv/CV_Gonzalo_Gimenez.pdf",
  photoPath: "/perfil-camisa.jpg",
  coverPath: "/portada.jpg",
  logoPath: "/logo-gg.png",
  aboutImagePath: "/about-systems.jpg",
  education:
    "Tecnicatura Superior en Desarrollo de Software, IFTS 11. Cursando Licenciatura en Ciencia de Datos en la Universidad de la Ciudad de Buenos Aires.",
  languages: "Inglés intermedio.",
  manifesto: "Perfil",
  aboutLead: "Producto, código y contexto real en la misma estrategia.",
  aboutParagraphs: [
    "Entiendo el problema, diseño la experiencia y lo llevo a código. No construyo pantallas sueltas. Construyo sistemas alrededor de operaciones reales.",
    "Entrelazo negocio, mercado, datos e inteligencia. Combino ejecución técnica, criterio de producto y lectura del negocio. También hago automatizaciones que entran en el trabajo de todos los días.",
  ],
} as const;
